apiVersion: apps/v1
kind: Deployment
metadata:
  name: malone-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malone-sidecar
  template:
    metadata:
      labels:
        app: malone-sidecar
    spec:
      containers:
        - name: malone-sidecar
          image: ghcr.io/tonygilkerson/malone-sidecar:test
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: serial-device
              mountPath: /dev/ttyUSB0
          securityContext:
            privileged: true
            # runAsUser: 0              
      volumes:
        - name: serial-device
          hostPath:
            path: /dev/ttyUSB0                            
