apiVersion: apps/v1
kind: Deployment
metadata:
  name: serial-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serial-gateway
  template:
    metadata:
      labels:
        app: serial-gateway
    spec:
      containers:
        - name: serial-gateway
          image: ghcr.io/tonygilkerson/serial-gateway:test
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: serial-device
              mountPath: /dev/ttyUSB0
          securityContext:
            privileged: true
            # runAsUser: 0              
      volumes:
        - name: serial-device
          hostPath:
            path: /dev/ttyUSB0                            
