apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: serial-gateway
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: serial-gateway
  endpoints:
  - port: http
    interval: 30s